[package]
name = "dummy-wrapper"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../../../kernel" }
encapfn = { path = "../../encapfn" }