[package]
name = "litex-ci-runner"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
rexpect = "0.4.0"
uuid = { version = "0.8.2", features = [ "v4" ] }