# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.
# Copyright Google LLC 2022.

[package]
name = "license-checker"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { features = ["derive"], version = "4.0.29" }
colored = "2.0.1"
ignore = "0.4"
thiserror = "1.0.44"

[dependencies.syntect]
default-features = false
features = ["default-syntaxes", "regex-onig", "yaml-load"]
version = "5.0.0"
